### ISSUE TITLE
The debug information is barely visible when Chrome theme is set to a dark one

### ISSUE THREAD

**Issue by cluka** [aurelia/inspector#1]
**I'm submitting a feature request**

* **Library Version:**
*

**Please tell us about your environment:**
* **Operating System:**
*

* **Node Version:**
*

* **NPM Version:**
*

* **JSPM OR Webpack AND Version**
*

* **Browser:**
Chrome 55 

* **Language:**
all

**Current behavior:**
The content of the debug visibility is low when Chrome theme is set to dark mode. Many texts are black or dark purple so is hard to distinguish and read.

**Expected/desired behavior:**

Make debug window content in contrast to the theme of the chrome dark/light mode.

* **What is the expected behavior?**
To clearly see the content of the debugger.

* **What is the motivation / use case for changing the behavior?**

**Comment by EisenbergEffect** [comment]
I don't think this is an Aurelia issue. We just use the standard console logging ability of the browser.

**Comment by cluka** [comment]
@EisenbergEffect I'm not talking about the console window. I'm talking about the Chrome addin (Aurelia-inspector). I see that it has its own css and html.
![inspector](https://cloud.githubusercontent.com/assets/1827208/22140756/b1f08d9c-deee-11e6-8261-32c4d81efe44.png)
