### ISSUE TITLE
Allow inspector to inspect aurelia web components

### ISSUE THREAD

**Issue by anupshah** [aurelia/inspector#13]
**I'm submitting a feature request**

It would be useful to support inspecting web components in the Inspector.

**Please tell us about your environment:**
* **Operating System:**
Windows 10
Linux/Lubuntu 18.04

* **Browser:**
all

**Current behavior:**

When inspecting elements to see the Aurelia inspector details, you inspect the various HTML elements using the in-built Chrome Developer tools.

**Expected/desired behavior:**

The current behaviour works, but it would be nice to inspect parts of a page, by clicking different areas, and the inspector highlighting the closest Aurelia web component.

* **What is the motivation / use case for changing the behavior?**

I think could help with productivity.

It is similar in idea to the very powerful (though sadly no longer maintained) illuminations for developers by Steve Rousey which helped tremendously with inspecting Ext JS components and components from other frameworks.

See screenshots here and here:
https://addons.mozilla.org/en-GB/firefox/addon/illuminations-for-developers/
https://chrome.google.com/webstore/detail/illuminations/hbhnkfhblakpfhcpepeoogmakimflibk?hl=en

I don't know if this goes against the spirit of Aurelia and web components being web standard features, but from an inspection point of view, sometimes it could be useful to see the Auerilia component POV when debugging, just to remove noise or just provide an alternative view...

**Comment by tamagosante** [comment]
@anupshah 
I, unfortunately don't fully understand the feature/improvement requested here.
If you are still interested, I'd welcome an elaboration

Now that 3 years, passed the links no longer work unfortunately.
I could only find this screenshot
![image](https://user-images.githubusercontent.com/30693990/147162618-c7521329-ba59-4ed3-85f5-cd91d5f93ee0.png)

**Comment by Alexander-Taran** [comment]
Inspector moved to https://github.com/brandonseydel/aurelia-inspector

@bigopon can be closed.. I guess

**Comment by anupshah** [comment]
Apologies, I completely missed your reply. Yeah, I just meant that if you can click on a component on the actual page, it would highlight the associated component information in the inspector - bit like inspecting an HTML element takes you to the HTML tab in the dev tools, you could be taken to a similar tab that shows you Aurelia components.

By way of example, that screenshot you found is similar - in Ext JS, the main blue "window" with the tree component on the left and the images in the main window are "Panels" so you can inspect their component hierarchy without needing to view the HTML (with options elsewhere to navigate to the underlying DOM if you need).

But since I raised this ticket, I've rarely had the opportunity to use Aurelia, so it may be that it is already planned or not as relevant any more, so I will close this for now and if I use it again (which might be soon), I will raise it with more details/examples, if needed.
