### ISSUE TITLE
Removed from Chrome Web Store

### ISSUE THREAD

**Issue by jboysen** [aurelia/inspector#17]
**I'm submitting a bug report**

Referring to this thread: https://discourse.aurelia.io/t/aurelia-inspector-for-chrome-has-disappeared/4042/3

Please get the Aurelia Inspector for Chrome back. Aurelia 2 is only alpha, so it doesn't make sense you only have support for that version right now.

**Comment by Alexander-Taran** [comment]
@jboysen what does not work for you with the new one?

**Comment by jboysen** [comment]
It doesn't show up as tab when I have it installed:
![image](https://user-images.githubusercontent.com/935849/129014757-69b6df8f-9d00-48f9-8069-ca117770ef33.png)

Reference for which Inspector is installed:
![image](https://user-images.githubusercontent.com/935849/129014673-58ba2148-2503-49c8-b972-0faea6aa20c1.png)

**Comment by Alexander-Taran** [comment]
@jboysen  Yep. Sometimes it does not.. But you can force it from plugins menu of chrome (right of the address bar)

**Comment by jboysen** [comment]
Thanks a lot, that worked 👍

**Comment by Alexander-Taran** [comment]
@jboysen your welcome
